import {
  FaArrowRight,
  FaRobot,
  FaSignOutAlt,
  FaStickyNote,
} from "react-icons/fa";
// Add your new node configurations here, No need to copy the folder multiple times for adding new Nodes.
// Future Scope: This node config can be appended based on form submission, hence nodes could be added by forms.
export const nodeConfigs = [
  {
    type: "inputNode",
    label: "Input",
    title: "Input Node",
    icon: <FaArrowRight />,
    inputHandles: [],
    outputHandles: [{ id: "value" }],
    fields: [
      { key: "inputName", label: "Name", default: "InputName" },
      {
        key: "inputType",
        label: "Type:",
        default: "Text",
        type: "select",
        options: ["Text", "File"],
      },
    ],
  },
  {
    type: "llmNode",
    label: "LLM",
    title: "LLM Node",
    icon: <FaRobot />,
    inputHandles: [{ id: "prompt" }],
    outputHandles: [{ id: "response" }],
    fields: [
      {
        key: "description",
        label: "Description",
        default: "This is a LLM Node",
      },
    ],
  },
  {
    type: "outputNode",
    label: "Output",
    title: "Output Node",
    icon: <FaSignOutAlt />,
    inputHandles: [{ id: "value" }],
    outputHandles: [],
    fields: [
      { key: "outputName", label: "Name:", default: "OutputName" },
      {
        key: "outputType",
        label: "Type:",
        default: "Text",
      },
    ],
  },
  {
    type: "textNode",
    label: "Text",
    title: "Text Node",
    icon: <FaStickyNote />,
    inputHandles: [],
    outputHandles: [{ id: "output" }],
    fields: [{ key: "text", label: "Text:", default: "{{input}}" }],
  },
  {
    type: "inputNodeA",
    label: "InputA",
    title: "Input Node A",
    icon: <FaArrowRight />,
    inputHandles: [],
    outputHandles: [{ id: "output" }],
    fields: [{ key: "text", label: "Text:", default: "{{input}}" }],
  },
  {
    type: "inputNodeB",
    label: "InputB",
    title: "Input Node B",
    icon: <FaArrowRight />,
    inputHandles: [],
    outputHandles: [{ id: "output" }],
    fields: [{ key: "text", label: "Text:", default: "{{input}}" }],
  },
  {
    type: "inputNodeC",
    label: "InputC",
    title: "Input Node C",
    icon: <FaArrowRight />,
    inputHandles: [],
    outputHandles: [{ id: "value" }],
    fields: [
      { key: "inputName", label: "Name", default: "InputName" },
      {
        key: "inputType",
        label: "Type:",
        default: "Text",
        type: "select",
        options: ["Text", "File"],
      },
    ],
  },
  {
    type: "outputNode1",
    label: "OutputA",
    title: "Output Node A",
    icon: <FaSignOutAlt />,
    inputHandles: [],
    outputHandles: [{ id: "output" }],
    fields: [{ key: "text", label: "Text:", default: "{{input}}" }],
  },
  {
    type: "outputNode2",
    label: "OutputB",
    title: " Output Node B",
    icon: <FaSignOutAlt />,
    inputHandles: [],
    outputHandles: [{ id: "output" }],
    fields: [{ key: "text", label: "Text:", default: "{{input}}" }],
  },
];
